name: drag_and_drop_windows
description: A Flutter plugin that adds drag-and-drop functionality for windows.
repository: https://github.com/arasan01/drag_and_drop_windows
version: 0.0.3

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: DragAndDropWindowsPlugin
